//
//  Strings.h
//  VKMessages
//
//  Created by Sergey Lenkov on 11.05.12.
//  Copyright (c) 2012 Sergey Lenkov. All rights reserved.
//

#ifndef VKMessages_Strings_h
#define VKMessages_Strings_h

#define VK_STR_OK                       NSLocalizedString(@"OK", @"")
#define VK_STR_LOGIN                    NSLocalizedString(@"LOGIN", @"")
#define VK_STR_LOGOUT                   NSLocalizedString(@"LOGOUT", @"")
#define VK_STR_MESSAGES                 NSLocalizedString(@"MESSAGES", @"")
#define VK_STR_AUDIO                    NSLocalizedString(@"AUDIO", @"")
#define VK_STR_PICTURES                 NSLocalizedString(@"PICTURES", @"")
#define VK_STR_PLAY                     NSLocalizedString(@"PLAY", @"")
#define VK_STR_STOP                     NSLocalizedString(@"STOP", @"")
#define VK_STR_DROP_PICTURES            NSLocalizedString(@"DROP_PICTURES", @"")
#define VK_STR_DROP_OVER_PICTURES       NSLocalizedString(@"DROP_OVER_PICTURES", @"")
#define VK_STR_SELECT_ALBUM             NSLocalizedString(@"SELECT_ALBUM", @"")
#define VK_STR_CANCEL                   NSLocalizedString(@"CANCEL", @"")
#define VK_STR_UPLOAD                   NSLocalizedString(@"UPLOAD", @"")
#define VK_STR_CHANGE                   NSLocalizedString(@"CHANGE", @"")
#define VK_STR_DELETE                   NSLocalizedString(@"DELETE", @"")
#define VK_STR_STATUS                   NSLocalizedString(@"STATUS", @"")
#define VK_STR_NEW_MESSAGE              NSLocalizedString(@"NEW_MESSAGE", @"")
#define VK_STR_SEND                     NSLocalizedString(@"SEND", @"")
#define VK_STR_DELETE_DIALOG_TITLE      NSLocalizedString(@"DELETE_DIALOG_TITLE", @"")
#define VK_STR_DELETE_DIALOG_TEXT       NSLocalizedString(@"DELETE_DIALOG_TEXT", @"")
#define VK_STR_SETTINGS_GENERAL         NSLocalizedString(@"SETTINGS_GENERAL", @"")
#define VK_STR_SETTINGS_ACCOUNT         NSLocalizedString(@"SETTINGS_ACCOUNT", @"")
#define VK_STR_SETTINGS_MESSAGES        NSLocalizedString(@"SETTINGS_MESSAGES", @"")
#define VK_STR_SETTINGS_AUDIO           NSLocalizedString(@"SETTINGS_AUDIO", @"")
#define VK_STR_SETTINGS_SHOW_AVATARS    NSLocalizedString(@"SETTINGS_SHOW_AVATARS", @"")
#define VK_STR_SETTINGS_SHOW_TIME       NSLocalizedString(@"SETTINGS_SHOW_TIME", @"")
#define VK_STR_SETTINGS_SHIFT_ENTER     NSLocalizedString(@"SETTINGS_SHIFT_ENTER", @"")
#define VK_STR_SETTINGS_START_AT_LOGIN  NSLocalizedString(@"SETTINGS_START_AT_LOGIN", @"")
#define VK_STR_SETTINGS_DOCK_ICON       NSLocalizedString(@"SETTINGS_DOCK_ICON", @"")
#define VK_STR_SETTINGS_STATUS_BAR_ICON NSLocalizedString(@"SETTINGS_STATUS_BAR_ICON", @"")
#define VK_STR_PASSWORD                 NSLocalizedString(@"PASSWORD", @"")
#define VK_STR_PHONE_OR_EMAIL           NSLocalizedString(@"PHONE_OR_EMAIL", @"")
#define VK_STR_SELECT_SONG              NSLocalizedString(@"SELECT_SONG", @"")
#define VK_STR_PICTURES_COUNT           NSLocalizedString(@"PICTURES_COUNT", @"")
#define VK_STR_PICTURES_SIZE            NSLocalizedString(@"PICTURES_SIZE", @"")
#define VK_STR_ENTER                    NSLocalizedString(@"ENTER", @"")
#define VK_STR_LAST_SEEN_USER           NSLocalizedString(@"LAST_SEEN_USER", @"")
#define VK_STR_USER_TYPING              NSLocalizedString(@"USER_TYPING", @"")
#define VK_STR_CITY                     NSLocalizedString(@"CITY", @"")
#define VK_STR_PHONE                    NSLocalizedString(@"PHONE", @"")
#define VK_STR_TWITTER                  NSLocalizedString(@"TWITTER", @"")
#define VK_STR_FACEBOOK                 NSLocalizedString(@"FACEBOOK", @"")
#define VK_STR_UNIVERSITY               NSLocalizedString(@"UNIVERSITY", @"")
#define VK_STR_BIRTHDAY                 NSLocalizedString(@"BIRTHDAY", @"")
#define VK_STR_SHOW_PROFILE             NSLocalizedString(@"SHOW_PROFILE", @"")
#define VK_STR_EMPTY_STATUS             NSLocalizedString(@"EMPTY_STATUS", @"")
#define VK_STR_MESSAGE_GROUP_FORMAT     NSLocalizedString(@"MESSAGE_GROUP_FORMAT", @"")
#define VK_STR_MADE_IN                  NSLocalizedString(@"MADE_IN", @"")
#define VK_STR_QUIT                     NSLocalizedString(@"QUIT", @"")
#define VK_STR_PREFERENCES              NSLocalizedString(@"PREFERENCES", @"")
#define VK_STR_OPEN_MESSAGES            NSLocalizedString(@"OPEN_MESSAGES", @"")
#define VK_STR_OPEN_AUDIO               NSLocalizedString(@"OPEN_AUDIO", @"")
#define VK_STR_OPEN_PHOTOS              NSLocalizedString(@"OPEN_PHOTOS", @"")
#define VK_STR_ABOUT                    NSLocalizedString(@"ABOUT", @"")
#define VK_STR_IMAGE_SIZE_NORMAL        NSLocalizedString(@"IMAGE_SIZE_NORMAL", @"")
#define VK_STR_IMAGE_SIZE_BIG           NSLocalizedString(@"IMAGE_SIZE_BIG", @"")
#define VK_STR_IMAGE_SIZE_ORIGINAL      NSLocalizedString(@"IMAGE_SIZE_ORIGINAL", @"")
#define VK_STR_NEW_ALBUM                NSLocalizedString(@"NEW_ALBUM", @"")
#define VK_STR_ADD_NEW_ALBUM            NSLocalizedString(@"ADD_NEW_ALBUM", @"")
#define VK_STR_CREATE_NEW_ALBUM         NSLocalizedString(@"CREATE_NEW_ALBUM", @"")
#define VK_STR_ALBUM_RIGHTS             NSLocalizedString(@"ALBUM_RIGHTS", @"")
#define VK_STR_COMMENTS_RIGHTS          NSLocalizedString(@"COMMENTS_RIGHTS", @"")
#define VK_STR_RIGHTS_ALL               NSLocalizedString(@"RIGHTS_ALL", @"")
#define VK_STR_RIGHTS_FRIENDS           NSLocalizedString(@"RIGHTS_FRIENDS", @"")
#define VK_STR_RIGHTS_EACHOTHER         NSLocalizedString(@"RIGHTS_EACHOTHER", @"")
#define VK_STR_RIGHTS_ME                NSLocalizedString(@"RIGHTS_ME", @"")
#define VK_STR_CAPTCHA                  NSLocalizedString(@"CAPTCHA", @"")
#define VK_STR_MESSAGE_PLACEHOLDER      NSLocalizedString(@"MESSAGE_PLACEHOLDER", @"")
#define VK_STR_SEARCH_PLACEHOLDER       NSLocalizedString(@"SEARCH_PLACEHOLDER", @"")
#define VK_STR_STATUS_PLACEHOLDER       NSLocalizedString(@"STATUS_PLACEHOLDER", @"")
#define VK_STR_ALBUM_NAME_PLACEHOLDER   NSLocalizedString(@"ALBUM_NAME_PLACEHOLDER", @"")
#define VK_STR_ALBUM_DESC_PLACEHOLDER   NSLocalizedString(@"ALBUM_DESC_PLACEHOLDER", @"")
#define VK_STR_REMEMBER_ME              NSLocalizedString(@"REMEMBER_ME", @"")
#define VK_STR_FORGOT_PASSWORD          NSLocalizedString(@"FORGOT_PASSWORD", @"")
#define VK_STR_REGISTER                 NSLocalizedString(@"REGISTER", @"")
#define VK_STR_NOTIFICATION_BUTTON      NSLocalizedString(@"NOTIFICATION_BUTTON", @"")
#define VK_STR_PHOTO_DIALOG             NSLocalizedString(@"PHOTO_DIALOG", @"")
#define VK_STR_AUDIO_DIALOG             NSLocalizedString(@"AUDIO_DIALOG", @"")
#define VK_STR_MESSAGE_DIALOG           NSLocalizedString(@"MESSAGE_DIALOG", @"")
#define VK_STR_VIDEO_DIALOG             NSLocalizedString(@"VIDEO_DIALOG", @"")
#define VK_STR_ABOUT_TERM               NSLocalizedString(@"ABOUT_TERM", @"")
#define VK_STR_ABOUT_DESIGN_TITLE       NSLocalizedString(@"ABOUT_DESIGN_TITLE", @"")
#define VK_STR_ABOUT_DESIGN_NAME        NSLocalizedString(@"ABOUT_DESIGN_NAME", @"")
#define VK_STR_ABOUT_PROG_TITLE         NSLocalizedString(@"ABOUT_PROG_TITLE", @"")
#define VK_STR_ABOUT_PROG_NAME          NSLocalizedString(@"ABOUT_PROG_NAME", @"")
#define VK_STR_ABOUT_MANAGER_TITLE      NSLocalizedString(@"ABOUT_MANAGER_TITLE", @"")
#define VK_STR_ABOUT_MANAGER_NAME       NSLocalizedString(@"ABOUT_MANAGER_NAME", @"")
#define VK_STR_ABOUT_OTHER_TITLE        NSLocalizedString(@"ABOUT_OTHER_TITLE", @"")
#define VK_STR_ABOUT_OTHER_NAME         NSLocalizedString(@"ABOUT_OTHER_NAME", @"")
#define VK_STR_ABOUT_COPY               NSLocalizedString(@"ABOUT_COPY", @"")
#define VK_STR_ABOUT_APP_NAME           NSLocalizedString(@"ABOUT_APP_NAME", @"")
#define VK_STR_ABOUT_APP_VERSION        NSLocalizedString(@"ABOUT_APP_VERSION", @"")
#define VK_STR_ABOUT_TITLE              NSLocalizedString(@"ABOUT_TITLE", @"")
#define VK_STR_NO_MORE_DIALOGS          NSLocalizedString(@"NO_MORE_DIALOGS", @"")
#define VK_STR_ERROR_LOADING_DIALOGS    NSLocalizedString(@"ERROR_LOADING_DIALOGS", @"")
#define VK_STR_LOAD_MORE                NSLocalizedString(@"LOAD_MORE", @"")
#define VK_STR_WE_IN                    NSLocalizedString(@"WE_IN", @"")
#define VK_STR_PAGE_IN                  NSLocalizedString(@"PAGE_IN", @"")
#define VK_STR_TWITTER_IN               NSLocalizedString(@"TWITTER_IN", @"")
#define VK_STR_VK_IN                    NSLocalizedString(@"VK_IN", @"")
#define VK_STR_FACEBOOK_IN              NSLocalizedString(@"FACEBOOK_IN", @"")
#define VK_STR_AND                      NSLocalizedString(@"AND", @"")
#define VK_STR_DELETE_CHAT_TEXT         NSLocalizedString(@"DELETE_CHAT_TEXT", @"")
#define VK_STR_YESTERDAY                NSLocalizedString(@"YESTERDAY", @"")
#define VK_STR_LOADING                  NSLocalizedString(@"LOADING", @"")
#define VK_STR_SEND_TO                  NSLocalizedString(@"SEND_TO", @"")
#define VK_STR_RESEND                   NSLocalizedString(@"RESEND", @"")
#define VK_STR_MESSAGE_WAS_NOT_SENT     NSLocalizedString(@"MESSAGE_WAS_NOT_SENT", @"")
#define VK_STR_WALL_POSTING             NSLocalizedString(@"WALL_POSTING", @"")
#define VK_STR_LOGIN_ERROR              NSLocalizedString(@"LOGIN_ERROR", @"")
#define VK_STR_MENU_NEW_DIALOG          NSLocalizedString(@"NEW_DIALOG", @"")
#define VK_STR_MENU_DELETE_DIALOG       NSLocalizedString(@"DELETE_DIALOG", @"")
#define VK_STR_FILE                     NSLocalizedString(@"FILE", @"")
#define VK_STR_DOCUMENT					NSLocalizedString(@"DOCUMENT", @"")
#define VK_STR_MAP   					NSLocalizedString(@"MAP", @"")
#define VK_STR_MESSAGE                  NSLocalizedString(@"MESSAGE", @"")
#define VK_STR_LOAD_MORE_DIALOGS        NSLocalizedString(@"LOAD_MORE_DIALOGS", @"")
#define VK_STR_OUTPUT_DEVICE            NSLocalizedString(@"OUTPUT_DEVICE", @"")

#endif
