name: Build macOS Application

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        sdk: [10.6, 10.13]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app  # Замените на нужную версию Xcode

    - name: Install dependencies
      run: |
        brew update
        brew install cmake  # или другие зависимости

    - name: Build application
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ matrix.sdk }}
        make

    - name: Create DMG
      run: |
        mkdir -p dist/${{ matrix.sdk }}
        hdiutil create dist/${{ matrix.sdk }}/YourApp-${{ matrix.sdk }}.dmg -volname "YourApp" -srcfolder build/YourApp.app -ov -format UDZO

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: YourApp-${{ matrix.sdk }}
        path: dist/${{ matrix.sdk }}/YourApp-${{ matrix.sdk }}.dmg

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: YourApp-10.6
        path: ./artifacts/10.6
    - uses: actions/download-artifact@v2
      with:
        name: YourApp-10.13
        path: ./artifacts/10.13

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset for SDK 10.6
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/10.6/YourApp-10.6.dmg
        asset_name: YourApp-10.6.dmg
        asset_content_type: application/x-apple-diskimage

    - name: Upload Release Asset for SDK 10.13
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/10.13/YourApp-10.13.dmg
        asset_name: YourApp-10.13.dmg
        asset_content_type: application/x-apple-diskimage
